defaults:
  - finetuning
  - _self_

mlflow: adapter_finetuning

model:
  adapters:
    finetuning:
      config: pfeiffer
      reduction_factor: ???
      with_head: True
    train:
      - finetuning