defaults:
  - adapter_finetuning

model:
  adapters:
    pretraining:
      pretrained_path: ???
      with_head: False
    finetuning:
      config: pfeiffer
      reduction_factor: 4
      with_head: True
    train:
      - finetuning