defaults:
  - config
  - data: ???
  - model_and_tokenizer
  - optimizer: triangular_lr
  - training
  - adapters  # ide gas
  - mlflow: adapter_sweep
  - _self_

labels_path: ???
num_labels: 19
evaluation_threshold: 0.75
message_column: preprocessed
epochs: ???

batch_size: 128

hydra:
  sweeper:
    params:
      optimizer.learning_rate: [8e-5, 1e-4, 2e-4, 3e-4, 6e-4]
      adapters.reduction_factor: [2, 4, 8, 16, 32]

