defaults:
  - config
  - data: ???
  - model_and_tokenizer
  - optimizer: triangular_lr
  - training
  - adapters  # ide gas
  - mlflow: adapter_sweep
  - early_stopping
  - _self_

labels_path: /data2/jvidakovic/dapters/data/labels.json
num_labels: 19
evaluation_threshold: 0.75
message_column: preprocessed
epochs: 100

batch_size: 128

