defaults:
  - finetuning
  - override mlflow: adapter_finetuning
  - _self_

model:
  adapters:
    finetuning:
      config: pfeiffer
      reduction_factor: ???
      with_head: True
    train:
      - finetuning