defaults:
  - misc
  - data: dummy
  - model: finetuning
  - tokenizer: default
  - optimizer: finetuning
  - training: finetuning
  - early_stopping: finetuning
  - mlflow: finetuning
  - _self_

# is this really it?