defaults:
  - config
  - data: dummy
  - model_and_tokenizer
  - optimizer: pretraining
  - training: pretraining_mrvica
  - early_stopping: pretraining
  - mlflow: pretraining
  - _self_

mlm_probability: 0.15
message_column: preprocessed