defaults:
  - misc
  - data: dummy
  - model: default
  - optimizer: pretraining
  - training: pretraining_mrvica
  - early_stopping: pretraining
  - mlflow: pretraining
  - _self_

mlm_probability: 0.15