defaults:
  - default
experiment: adapter_finetuning
run_name: '[A-FT] BS=${training.per_device_train_batch_size}; LR=${optimizer.learning_rate}; RF=${model.adapters.finetuning.reduction_factor}'
run_description: 'Adapter finetuning.'