defaults:
  - default
experiment: adapter_finetuning
run_name: '[A-FT] LR=${optimizer.learning_rate}; WD=${optimizer.weight_decay}; RF=${adapters.reduction_factor}'
run_description: 'Fine-tuning adapters with big batch size (BS=${per_device_train_batch_size}) and learning rate (LR=${optimizer.learning_rate}).'
