tracking_uri: http://localhost:34567
tags:
  batch_size: ${per_device_train_batch_size}
  learning_rate: ${optimizer.learning_rate}
  weight_decay: ${optimizer.weight_decay}
  epochs: ${epochs}
  optional early_stopping_patience: ${early_stopping.patience}
  warmup_percentage: ${optimizer.warmup_percentage}
  optional reduction_factor: ${adapters.reduction_factor}